name: archethic_dapp_framework_flutter
description: An internal framework for archethic flutter development
homepage: https://github.com/archethic-foundation/archethic-dapp-framework-flutter

version: 0.0.1+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add beautiful animated effects & builders in Flutter, via an easy, customizable, unified API.
  flutter_animate: ^4.5.0

  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.10

  # Wave animation
  wave: ^0.2.2

flutter:
  generate: true
  uses-material-design: true
