name: archethic_dapp_framework_flutter
description: An internal framework for archethic flutter development
homepage: https://github.com/archethic-foundation/archethic-dapp-framework-flutter

version: 1.2.14

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  # Archethic dart library for Flutter based on Official Archethic Javascript library for Node and Browser

  archethic_lib_dart: ^3.4.2
  #archethic_lib_dart:
  #  git:
  #    url: https://github.com/archethic-foundation/libdart.git
  #    ref: dev
  #archethic_lib_dart:
  #  path: ../libdart-2

  # A client dart library to interact with Archethic Wallet RPC API.
  archethic_wallet_client: ^2.0.8
  #archethic_wallet_client:
  #  path: ../archethic-wallet-client-dart

  # Compression
  archive: ^3.4.10

  # Flutter widget that automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0

  flutter:
    sdk: flutter

  # Add beautiful animated effects & builders in Flutter, via an easy, customizable, unified API.
  flutter_animate: ^4.5.0

  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Annotations for the freezed code-generator. This package does nothing without freezed too
  freezed_annotation: ^2.4.1

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App
  get_it: ^7.6.7

  # Gradient borders for inputs and containers. Borders package integrated with a basic flutter widgets as a container and input decorations. Easy in use, platform independent.
  gradient_borders: ^1.0.0

  # Hive is a lightweight and blazing fast key-value database written in pure Dart
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^1.2.1

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.19.0

  # Classes and helper functions that support JSON code generation via the `json_serializable` package
  json_annotation: ^4.8.1

  # A Flutter plugin for rendering an animated and customizable starfield on a dark background.
  lit_starfield: ^0.1.1

  # Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android
  package_info_plus: ^6.0.0

  # A package exposing annotations for riverpod_generator
  riverpod_annotation: ^2.3.5

  # Bar indicator made of a series of selected and unselected steps
  step_progress_indicator: ^1.0.2

  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes
  url_launcher: ^6.2.5

  # Wave animation
  wave: ^0.2.2

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.8
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.4.7
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
  # A code generator for Riverpod. This both simplifies the syntax empowers it, such as allowing stateful hot-reload.
  riverpod_generator: ^2.4.0
  # Automated tests
  test: ^1.25.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/src/domain/repositories/tokens/verified_tokens.json
    - lib/src/domain/repositories/tokens/ucids_tokens.json
    - lib/src/domain/repositories/tokens/def_tokens.json
